=== 有类型选项和参数

描述 {@link io.vertx.core.cli.Option} 和 {@link io.vertx.core.cli.Argument} 类是无类型的，这意味着仅读取String值。
{@link io.vertx.core.cli.TypedOption} 和 {@link io.vertx.core.cli.TypedArgument} 可以指定一个类型，因此（String）原始值将转换为指定的类型。

在 {@link io.vertx.core.cli.CLI} 定义中使用 {@link io.vertx.core.cli.TypedOption} 和 {@link io.vertx.core.cli.TypedArgument}
，而不是
{@link io.vertx.core.cli.Option} 和 {@link io.vertx.core.cli.Argument} 。

[source,java]
----
{@link examples.cli.TypedCLIExamples#example1}
----

然后，您可以按下边方式获取转换的值：

[source,java]
----
{@link examples.cli.TypedCLIExamples#example2}
----

Vert.x CLI可以转换的类：

* 具有单个
{@link java.lang.String} 参数的构造函数，例如 {@link java.io.File} 或 {@link io.vertx.core.json.JsonObject}
* 使用静态的`from`或`fromString`方法
* 使用静态`valueOf`方法，如基础类型和枚举

此外，您可以实现自己的转换器（ {@link io.vertx.core.cli.converters.Converter} ）并指定CLI使用此转换器：

[source,java]
----
{@link examples.cli.TypedCLIExamples#example3}
----

对于布尔值，布尔值将被评定为`true`:`on`，`yes`，`1`，`true`。

若您的一个选项是 `enum` 类型，则（系统）会自动计算一组选项。

=== 使用注解

您还可以使用注解定义CLI。在类和 *setter* 方法上使用注解来定义：

[source, java]
----
&#64;Name("some-name")
&#64;Summary("some short summary.")
&#64;Description("some long description")
public class AnnotatedCli {

  private boolean flag;
  private String name;
  private String arg;

 &#64;Option(shortName = "f", flag = true)
 public void setFlag(boolean flag) {
   this.flag = flag;
 }

 &#64;Option(longName = "name")
 public void setName(String name) {
   this.name = name;
 }

 &#64;Argument(index = 0)
 public void setArg(String arg) {
  this.arg = arg;
 }
}
----

注解后，您可以使用以下命令来定义 {@link io.vertx.core.cli.CLI} 并注入值：

[source,java]
----
{@link examples.cli.TypedCLIExamples#example4}
----
