== DNS 客户端

通常情况下，您需要以异步方式来获取DNS信息。
但不幸的是，Java 虚拟机本身附带的API是不可能的，因此Vert.x提供了它自己的完全异步解析DNS的API。

若要获取 `DnsClient` 实例，您可以通过 `Vertx` 实例来创建一个。

[source,$lang]
----
{@link examples.DNSExamples#example1}
----

You can also create the client with options and configure the query timeout.

[source,$lang]
----
{@link examples.DNSExamples#example1_}
----

Creating the client with no arguments or omitting the server address will use the address of the server used internally
for non blocking address resolution.

[source,$lang]
----
{@link examples.DNSExamples#example1__}
----

请注意，您可以传入 `InetSocketAddress` 参数的变量，以指定多个的DNS服务器来尝试查询解析DNS。它将按照此处指定的相同顺序查询DNS服务器，若在使用上一个DNS服务器解析时出现了错误，下一个将会被继续调用。

=== lookup

当尝试为一个指定名称元素获取A（ipv4）或 AAAA（ipv6）记录时，第一条被返回的（记录）将会被使用。它的操作方式和操作系统上使用 `nslookup` 类似。

要为 `vertx.io` 获取 A/AAAA 记录，您需要像下面那样做：

[source,$lang]
----
{@link examples.DNSExamples#example2}
----

=== lookup4

尝试查找给定名称的A（ipv4）记录。第一个返回的（记录）将会被使用，因此它的操作方式与操作系统上使用`nslookup`类似。

要查找 `vertx.io` 的A记录，您需要像下面那样做：

[source,$lang]
----
{@link examples.DNSExamples#example3}
----

=== lookup6

尝试查找给定名称的 AAAA（ipv6）记录。第一个返回的（记录）将会被使用，因此它的操作方式与在操作系统上使用 `nslookup` 类似。

要查找 `vertx.io` 的 AAAA记录，您需要像下面那样做：

[source,$lang]
----
{@link examples.DNSExamples#example4}
----

=== resolveA

尝试解析给定名称的所有A（ipv4）记录，这与在unix操作系统上使用`dig`类似。

要查找`vertx.io`的所有A记录，您通常会执行以下操作：

[source,$lang]
----
{@link examples.DNSExamples#example5}
----

=== resolveAAAA

尝试解析给定名称的所有AAAA（ipv6）记录，这与在Unix操作系统上使用`dig`类似。

要查找`vertx.io`的所有AAAA记录，您通常会执行以下操作：


[source,$lang]
----
{@link examples.DNSExamples#example6}
----

=== resolveCNAME

尝试解析给定名称的所有CNAME记录，这与在Unix操作系统上使用`dig`类似。

要查找`vertx.io`的所有CNAME记录，您通常会执行以下操作：

[source,$lang]
----
{@link examples.DNSExamples#example7}
----

=== resolveMX

尝试解析给定名称的所有MX记录，MX记录用于定义哪个邮件服务器接受给定域的电子邮件。

要查找您常用执行的`vertx.io`的所有MX记录：

[source,$lang]
----
{@link examples.DNSExamples#example8}
----

请注意，列表将包含按照它们优先级排序的 {@link io.vertx.core.dns.MxRecord} ，这意味着列表中优先级低的MX记录会第一个优先出现在列表中。
means MX records with smaller priority coming first in the List.

{@link io.vertx.core.dns.MxRecord} 允许您通过下边提供的方法访问MX记录的优先级和名称：

[source,$lang]
----
{@link examples.DNSExamples#example9}
----

=== resolveTXT

尝试解析给定名称的所有TXT记录，TXT记录通常用于定义域的额外信息。

要解析`vertx.io`的所有TXT记录，您可以使用下边几行：

[source,$lang]
----
{@link examples.DNSExamples#example10}
----

=== resolveNS

尝试解析给定名称的所有NS记录，NS记录指定哪个DNS服务器托管给定域的DNS信息。

要解析`vertx.io`的所有NS记录，您可以使用下边几行：

[source,$lang]
----
{@link examples.DNSExamples#example11}
----

=== resolveSRV

尝试解析给定名称的所有SRV记录，SRV记录用于定义服务端口和主机名等额外信息。一些协议需要这个额外信息。

要查找`vertx.io`的所有SRV记录，您通常会执行以下操作：

[source,$lang]
----
{@link examples.DNSExamples#example12}
----

请注意，列表将包含按照它们优先级排序的 {@link io.vertx.core.dns.SrvRecord} ，这意味着优先级低的记录会第一个优先出现在列表中。


{@link io.vertx.core.dns.SrvRecord} 允许您访问SRV记录本身中包含的所有信息：

[source,$lang]
----
{@link examples.DNSExamples#example13}
----

有关详细信息，请参阅API文档。

=== resolvePTR

尝试解析给定名称的PTR记录，PTR记录将`ipaddress`映射到名称。

要解析IP地址`10.0.0.1`的PTR记录，您将使用`1.0.0.10.in-addr.arpa`的PTR概念。

[source,$lang]
----
{@link examples.DNSExamples#example14}
----

=== reverseLookup

尝试对ipaddress进行反向查找，这与解析PTR记录类似，但是允许您只传递ipaddress，而不是有效的PTR查询字符串。

要做ipaddress 10.0.0.1的反向查找类似的事：


[source,$lang]
----
{@link examples.DNSExamples#example15}
----

include::override/dns.adoc[]
