== 编写 TCP 服务端和客户端

Vert.x允许您很容易编写非阻塞的TCP客户端和服务器。

=== 创建 TCP 服务端

最简单地使用所有默认配置项创建 TCP 服务端的方式如下：

[source,$lang]
----
{@link examples.NetExamples#example1}
----

=== 配置 TCP 服务端

若您不想使用默认配置，可以在创建时通过传入一个 {@link io.vertx.core.net.NetServerOptions}
实例来配置服务器：

[source,$lang]
----
{@link examples.NetExamples#example2}
----

=== 启动服务端监听

要告诉服务端监听传入的请求，您可以使用其中一个 {@link io.vertx.core.net.NetServer#listen}
方法。

让服务器监听配置项指定的主机和端口：

[source,$lang]
----
{@link examples.NetExamples#example3}
----

或在调用 `listen` 方法时指定主机和端口号，忽略配置项中的配置：

[source,$lang]
----
{@link examples.NetExamples#example4}
----

默认主机名是 `0.0.0.0` ，它表示：监听所有可用地址。默认端口号是 `0` ，这也是一个特殊值，它告诉服务器随机选择并监听一个本地没有被占用的端口。

实际的绑定也是异步的，因此服务器在调用了 `listen` 方法的一段时间之后才会实际开始监听。

若您希望在服务器实际监听时收到通知，您可以在调用 `listen` 方法时提供一个处理器。例如：

[source,$lang]
----
{@link examples.NetExamples#example5}
----

=== 监听随机端口

若设置监听端口为 `0` ，服务器将随机寻找一个没有使用的端口来监听。

可以调用 {@link io.vertx.core.net.NetServer#actualPort()} 方法来获得服务器实际监听的端口：

[source,$lang]
----
{@link examples.NetExamples#example5_1}
----

=== 接收传入连接的通知

若您想要在连接创建完时收到通知，则需要设置一个 {@link io.vertx.core.net.NetServer#connectHandler(io.vertx.core.Handler)} :

[source,$lang]
----
{@link examples.NetExamples#example6}
----

当连接成功时，您可以在回调函数中处理得到的 {@link io.vertx.core.net.NetSocket} 实例。

这是一个代表了实际连接的套接字接口，它允许您读取和写入数据、以及执行各种其他操作，如关闭 Socket。

=== 从Socket读取数据

您可以在Socket上调用 {@link io.vertx.core.net.NetSocket#handler(io.vertx.core.Handler)} 方法来设置用于读取数据的处理器。

每次 Socket 接收到数据时，会以 {@link io.vertx.core.buffer.Buffer} 对象为参数调用处理器。

[source,$lang]
----
{@link examples.NetExamples#example7}
----

=== 向Socket中写入数据

您可使用 {@link io.vertx.core.net.NetSocket#write} 方法写入数据到Socket：

[source,$lang]
----
{@link examples.NetExamples#example8}
----

写入操作是异步的，可能调用 `write` 方法返回过后一段时间才会发生。

=== 关闭处理器

若您想要在 Socket 关闭时收到通知，可以设置一个 {@link io.vertx.core.net.NetSocket#closeHandler(io.vertx.core.Handler)} :

[source,$lang]
----
{@link examples.NetExamples#example9_1}
----

=== 处理异常

您可以设置一个 {@link io.vertx.core.net.NetSocket#exceptionHandler(io.vertx.core.Handler)} 用以在发生任何异常的时候接收异常信息。

=== Event Bus 写处理器

每个 Socket 会自动在Event Bus中注册一个处理器，当这个处理器中收到任意 `Buffer` 时，它会将数据写入到 Socket。

这意味着您可以通过向这个地址发送 `Buffer` 的方式，从不同的 Verticle 甚至是不同的 Vert.x 实例中向指定的 Socket 发送数据。

处理器的地址由 {@link io.vertx.core.net.NetSocket#writeHandlerID()} 方法提供。

=== 本地和远程地址

您可以通过 {@link io.vertx.core.net.NetSocket#localAddress()} 方法获取 {@link io.vertx.core.net.NetSocket} 的本地地址，

通过 {@link io.vertx.core.net.NetSocket#remoteAddress()} 方法获取 {@link io.vertx.core.net.NetSocket} 的远程地址（即连接的另一端的地址）。

=== 发送文件或 Classpath 中的资源

您可以直接通过 {@link io.vertx.core.net.NetSocket#sendFile} 方法将文件和 classpath 中的资源写入Socket。
这种做法是非常高效的，它可以被操作系统内核直接处理。

请阅读 <<classpath, 从 Classpath 访问文件>> 章节了解类路径的限制或禁用它。

[source,$lang]
----
{@link examples.NetExamples#example10}
----

=== 流式的Socket

{@link io.vertx.core.net.NetSocket} 接口继承了 {@link io.vertx.core.streams.ReadStream} 和
{@link io.vertx.core.streams.WriteStream} 接口，因此您可以将它套用（pump）到其他的读写流上。

有关更多信息，请参阅 <<streams, 流和管道>>  章节。

=== 升级到 SSL/TLS 连接

一个非SSL/TLS连接可以通过 {@link io.vertx.core.net.NetSocket#upgradeToSsl(io.vertx.core.Handler)} 方法升级到SSL/TLS连接。

必须为服务器或客户端配置SSL/TLS才能正常工作。请参阅 <<ssl, SSL/TLS>> 章节来获取详细信息。
for more information.

=== 关闭 TCP 服务端

您可以调用 {@link io.vertx.core.net.NetServer#close()} 方法关闭服务端。关闭操作将关闭所有打开的连接并释放所有服务端资源。

关闭操作也是异步的，可能直到方法调用返回过后一段时间才会实际关闭。若您想在实际关闭完成时收到通知，那么您可以传递一个处理器。

当关闭操作完成后，绑定的处理器将被调用：

[source,$lang]
----
{@link examples.NetExamples#example9}
----

=== Verticle中的自动清理

若您在 Verticle 内创建了 TCP 服务端和客户端，它们将会在Verticle 撤销时自动被关闭。

=== 扩展 - 共享 TCP 服务端

任意一个 TCP 服务端中的处理器总是在相同的 Event Loop 线程上执行。

这意味着如果您在多核的服务器上运行，并且只部署了一个实例，那么您的服务器上最多只能使用一个核。

为了利用更多的服务器核，您将需要部署更多的服务器实例。

您可以在代码中以编程方式实例化更多（Server的）实例：

[source,$lang]
----
{@link examples.NetExamples#example11}
----

如果您使用的是 Verticle，您可以通过在命令行上使用 `-instances` 选项来简单部署更多的服务器实例：

 vertx run com.mycompany.MyVerticle -instances 10

或者使用编程方式部署您的 Verticle 时：

[source,$lang]
----
{@link examples.NetExamples#example12}
----

一旦您这样做，您将发现echo服务器在功能上与之前相同，但是服务器上的所有核都可以被利用，并且可以处理更多的工作。

在这一点上，您可能会问自己：**如何让多台服务器在同一主机和端口上侦听？尝试部署一个以上的实例时真的不会遇到端口冲突吗？**

*Vert.x在这里有一点魔法。*

当您在与现有服务器相同的主机和端口上部署另一个服务器实例时，实际上它并不会尝试创建在同一主机/端口上侦听的新服务器实例。

相反，它内部仅仅维护一个服务器实例。当传入新的连接时，它以轮询的方式将其分发给任意一个连接处理器处理。

因此，Vert.x TCP 服务端可以水平扩展到多个核，并且每个实例保持单线程环境不变。

=== 创建 TCP 客户端

使用所有默认选项创建 TCP 客户端的最简单方法如下：

[source,$lang]
----
{@link examples.NetExamples#example13}
----

=== 配置 TCP 客户端

如果您不想使用默认值，则可以在创建实例时传入 {@link io.vertx.core.net.NetClientOptions}
给客户端：

[source,$lang]
----
{@link examples.NetExamples#example14}
----

=== 创建连接

您可以使用 {@link io.vertx.core.net.NetClient#connect(int,java.lang.String,io.vertx.core.Handler)} ,
方法创建到服务器的连接。请指定服务器的端口和主机，以及用于处理
{@link io.vertx.core.net.NetSocket} 的处理器。当连接成功或失败时处理器会被调用。

[source,$lang]
----
{@link examples.NetExamples#example15}
----

=== 配置连接重试

可以将客户端配置为在无法连接的情况下自动重试。
这是通过 {@link io.vertx.core.net.NetClientOptions#setReconnectInterval(long)} 和
{@link io.vertx.core.net.NetClientOptions#setReconnectAttempts(int)} 方法配置的。

NOTE: *注意：目前如果连接失效，Vert.x将不尝试重新连接。重新连接尝试和时间间隔仅适用于创建初始连接。*

[source,$lang]
----
{@link examples.NetExamples#example16}
----

默认情况下，多个连接尝试是被禁用的。

[[logging_network_activity]]
=== 记录网络活动

网络活动可以被记录下来，用于调试：

[source,$lang]
----
{@link examples.NetExamples#exampleNetworkActivityLoggingOnServer}
----

对于客户端：

[source,$lang]
----
{@link examples.NetExamples#exampleNetworkActivityLoggingOnClient}
----

Netty 使用 `DEBUG` 级别和 `io.netty.handler.logging.LoggingHandler` 名称来记录网络活动。使用网络活动记录时，需要注意以下几点：

* 日志的记录是由Netty而不是Vert.x的日志来执行
* 这个功能不能用于生产环境

您应该阅读 <<netty-logging, Netty 日志记录>> 章节来了解详细信息。

[[ssl]]
=== 配置服务端和客户端以使用SSL/TLS

TCP 客户端和服务端可以通过配置来使用 http://en.wikipedia.org/wiki/Transport_Layer_Security[TLS（传输层安全性协议）]
。早期版本的TLS被称为SSL。

无论是否使用SSL/TLS，服务器和客户端的API都是相同的。通过创建客户端/服务器时使用的 {@link io.vertx.core.net.NetClientOptions} 或 {@link io.vertx.core.net.NetServerOptions} 来启用TLS/SSL。

==== 在服务端启用SSL/TLS

您需要设置 {@link io.vertx.core.net.NetServerOptions#setSsl(boolean) ssl} 配置项来启用 SSL/TLS。

默认是禁用的。

==== 指定服务端的密钥/证书

SSL/TLS 服务端通常向客户端提供证书，以便验证服务端的身份。

可以通过以下几种方式为服务端配置证书/密钥：

第一种方法是指定包含证书和私钥的Java密钥库位置。

可以使用 JDK 附带的 http://docs.oracle.com/javase/6/docs/technotes/tools/solaris/keytool.html[keytool]
实用程序来管理Java密钥存储。

还应提供密钥存储的密码：

[source,$lang]
----
{@link examples.NetExamples#example17}
----

或者，您可以自己读取密钥库到一个 `Buffer` ，并将它直接提供给 `JksOptions` ：

[source,$lang]
----
{@link examples.NetExamples#example18}
----

PKCS＃12格式的密钥/证书 (http://en.wikipedia.org/wiki/PKCS_12) ，通常为 `.pfx` 或 `.p12` 扩展名）也可以用与JKS密钥存储相似的方式加载：

[source,$lang]
----
{@link examples.NetExamples#example19}
----

也支持通过 `Buffer` 来配置：

[source,$lang]
----
{@link examples.NetExamples#example20}
----

另外一种分别提供服务器私钥和证书的方法是使用 `.pem` 文件。

[source,$lang]
----
{@link examples.NetExamples#example21}
----

也支持通过 `Buffer` 来配置：

[source,$lang]
----
{@link examples.NetExamples#example22}
----

PKCS8, PKCS1 and X.509 certificates wrapped in a PEM block formats are supported.

WARNING: 请记住pem的配置和私钥是不加密的。

==== 指定服务器信任

SSL/TLS 服务端可以使用证书颁发机构来验证客户端的身份。

证书颁发机构可通过多种方式为服务端配置。

可使用JDK随附的 http://docs.oracle.com/javase/6/docs/technotes/tools/solaris/keytool.html[keytool]
实用程序来管理Java 受信存储。

还应提供受信存储的密码：

[source,$lang]
----
{@link examples.NetExamples#example23}
----

或者您可以自己读取受信存储到 `Buffer` ，并将它直接提供：

[source,$lang]
----
{@link examples.NetExamples#example24}
----

PKCS＃12格式的密钥/证书 (http://en.wikipedia.org/wiki/PKCS_12) ，通常为 `.pfx` 或 `.p12` 扩展名）也可以用与JKS密钥存储相似的方式加载：

[source,$lang]
----
{@link examples.NetExamples#example25}
----

也支持通过 `Buffer` 来配置：

[source,$lang]
----
{@link examples.NetExamples#example26}
----

另一种提供服务器证书颁发机构的方法是使用一个 `.pem` 文件列表。

[source,$lang]
----
{@link examples.NetExamples#example27}
----

也支持通过 `Buffer` 来配置：

[source,$lang]
----
{@link examples.NetExamples#example28}
----

==== 客户端启用SSL/TLS

客户端也可以轻松地配置为SSL。使用SSL和使用标准套接字具有完全相同的API。

若要启用 `NetClient` 上的SSL，可调用函数 `setSSL(true)` 。

==== 客户端受信配置

若客户端将 {@link io.vertx.core.net.ClientOptionsBase#setTrustAll trustALl} 设置为 `true` ，则客户端将信任所有服务端证书。
连接仍然会被加密，但这种模式很容易受到中间人攻击。即您无法确定您正连接到谁，请谨慎使用。默认值为 `false` 。

[source,$lang]
----
{@link examples.NetExamples#example29}
----

若客户端没有设置 {@link io.vertx.core.net.ClientOptionsBase#setTrustAll trustAll} ，则必须配置客户端受信存储，并且受信客户端应该包含服务器的证书。

默认情况下，客户端禁用主机验证。要启用主机验证，请在客户端上设置使用的算法（目前仅支持HTTPS和LDAPS）：

[source,$lang]
----
{@link examples.NetExamples#example46}
----

和服务器配置相同，也可通过以下几种方式配置受信客户端：

第一种方法是指定包含证书颁发机构的Java受信库的位置。

它只是一个标准的Java密钥存储，与服务器端的密钥存储相同。通过在
{@link io.vertx.core.net.JksOptions jks options} 上使用 {@link io.vertx.core.net.JksOptions#setPath path}
设置客户端受信存储位置。如果服务器在连接期间提供不在客户端受信存储中的证书，则尝试连接将不会成功。

[source,$lang]
----
{@link examples.NetExamples#example30}
----

它也支持 `Buffer` 的配置：

[source,$lang]
----
{@link examples.NetExamples#example31}
----

PKCS＃12格式的密钥/证书 (http://en.wikipedia.org/wiki/PKCS_12) ，通常为 `.pfx` 或 `.p12` 扩展名）也可以用与JKS密钥存储相似的方式加载：

[source,$lang]
----
{@link examples.NetExamples#example32}
----

也支持通过 `Buffer` 来配置：

[source,$lang]
----
{@link examples.NetExamples#example33}
----

另一种提供服务器证书颁发机构的方法是使用一个 `.pem` 文件列表。

[source,$lang]
----
{@link examples.NetExamples#example34}
----

也支持通过 `Buffer` 来配置：

[source,$lang]
----
{@link examples.NetExamples#example35}
----

==== 指定客户端的密钥/证书

如果服务器需要客户端认证，那么当连接时，客户端必须向服务器提供自己的证书。可通过以下几种方式配置客户端：

第一种方法是指定包含密钥和证书的Java 密钥库的位置，它只是一个常规的Java 密钥存储。使用 {@link io.vertx.core.net.JksOptions jks options} 上的功能路径设置客户端密钥库位置 {@link io.vertx.core.net.JksOptions#setPath(java.lang.String) path} 。

[source,$lang]
----
{@link examples.NetExamples#example36}
----

也支持通过 `Buffer` 来配置：

[source,$lang]
----
{@link examples.NetExamples#example37}
----

PKCS＃12格式的密钥/证书 (http://en.wikipedia.org/wiki/PKCS_12) ，通常为 `.pfx` 或 `.p12` 扩展名）也可以用与JKS密钥存储相似的方式加载：

[source,$lang]
----
{@link examples.NetExamples#example38}
----

也支持通过 `Buffer` 来配置：

[source,$lang]
----
{@link examples.NetExamples#example39}
----

另一种单独提供服务器私钥和证书的方法是使用 `.pem` 文件。

[source,$lang]
----
{@link examples.NetExamples#example40}
----

也支持通过 `Buffer` 来配置：

[source,$lang]
----
{@link examples.NetExamples#example41}
----

请记住 `pem` 的配置和私钥是不加密的。

==== 用于测试和开发目的的自签名证书

CAUTION: 不要在生产设置中使用，这里生成的密钥非常不安全。

在运行单元/集成测试或是运行开发版的应用程序时都经常需要自签名证书。

{@link io.vertx.core.net.SelfSignedCertificate} 可用于提供自签名PEM证书，并可以提供
give {@link io.vertx.core.net.KeyCertOptions} 和 {@link io.vertx.core.net.TrustOptions} configurations 配置：

[source,$lang]
----
{@link examples.NetExamples#example48}
----

客户端也可配置为信任所有证书：

[source,$lang]
----
{@link examples.NetExamples#example49}
----

自签名证书也适用于其他基于TCP的协议，如HTTPS：

[source,$lang]
----
{@link examples.NetExamples#example50}
----

==== 待撤销证书颁发机构

可以通过配置证书吊销列表（CRL）来吊销不再被信任的证书机构。 {@link io.vertx.core.net.NetClientOptions#addCrlPath(java.lang.String) crlPath} 配置了使用的CRL：
the crl list to use:

[source,$lang]
----
{@link examples.NetExamples#example42}
----

也支持通过 `Buffer` 来配置：

[source,$lang]
----
{@link examples.NetExamples#example43}
----

==== 配置密码套件

默认情况下，TLS配置将使用运行Vert.x的JVM 密码套件，该密码套件可以配置一套启用的密码：

[source,$lang]
----
{@link examples.NetExamples#example44}
----

密码套件可在 {@link io.vertx.core.net.NetServerOptions} 或 {@link io.vertx.core.net.NetClientOptions} 配置项中指定。

==== 配置TLS协议版本

默认情况下，TLS配置将使用以下协议版本：SSLv2Hello、TLSv1、TLSv1.1 和 TLSv1.2。 协议版本可以通过显式添加启用协议进行配置：

[source,$lang]
----
{@link examples.NetExamples#example45}
----

协议版本可在 {@link io.vertx.core.net.NetServerOptions} 或 {@link io.vertx.core.net.NetClientOptions} 配置项中指定。

==== SSL引擎

引擎实现可以配置为使用 https://www.openssl.org[OpenSSL] 而不是JDK实现（来支持SSL）。 OpenSSL提供比JDK引擎更好的性能和CPU使用率、以及JDK版本独立性。

引擎选项可使用：

- 当 {@link io.vertx.core.net.TCPSSLOptions#getSslEngineOptions()} 被设置时，使用该选项
- 否则使用 {@link io.vertx.core.net.JdkSSLEngineOptions}

[source,$lang]
----
{@link examples.NetExamples#exampleSSLEngine}
----

==== Server Name Indication (SNI)

Server Name Indication (SNI) is a TLS extension by which a client specifies a hostname attempting to connect: during
the TLS handshake the client gives a server name and the server can use it to respond with a specific certificate
for this server name instead of the default deployed certificate.
If the server requires client authentication the server can use a specific trusted CA certificate depending on the
indicated server name.

When SNI is active the server uses

* the certificate CN or SAN DNS (Subject Alternative Name with DNS) to do an exact match, e.g `www.example.com`
* the certificate CN or SAN DNS certificate to match a wildcard name, e.g `*.example.com`
* otherwise the first certificate when the client does not present a server name or the presented server name cannot be matched

When the server additionally requires client authentication:

* if {@link io.vertx.core.net.JksOptions} were used to set the trust options
 ( {@link io.vertx.core.net.NetServerOptions#setTrustOptions options} ) then an exact match with the trust store
 alias is done
* otherwise the available CA certificates are used in the same way as if no SNI is in place

You can enable SNI on the server by setting {@link io.vertx.core.net.NetServerOptions#setSni(boolean)} to `true` and
configured the server with multiple key/certificate pairs.

Java KeyStore files or PKCS12 files can store multiple key/cert pairs out of the box.

[source,$lang]
----
{@link examples.NetExamples#configureSNIServer}
----

{@link io.vertx.core.net.PemKeyCertOptions} can be configured to hold multiple entries:

[source,$lang]
----
{@link examples.NetExamples#configureSNIServerWithPems}
----

The client implicitly sends the connecting host as an SNI server name for Fully Qualified Domain Name (FQDN).

You can provide an explicit server name when connecting a socket

[source,$lang]
----
{@link examples.NetExamples#useSNIInClient}
----

It can be used for different purposes:

* present a server name different than the server host
* present a server name while connecting to an IP
* force to present a server name when using shortname

==== 应用层协议协商 (ALPN)

ALPN(Application-Layer Protocol Negotiation)是应用层协议协商的TLS扩展，它被HTTP/2使用：在TLS握手期时，客户端给出其接受的应用协议列表，之后服务器使用它所支持的协议响应。

If you are using Java 9, you are fine and you can use HTTP/2 out of the box without extra steps.

标准的Java 8不支持ALPN，所以ALPN应该通过其他方式启用：

- OpenSSL支持
- Jetty-ALPN支持

引擎选项可使用:

- 当 {@link io.vertx.core.net.TCPSSLOptions#getSslEngineOptions()} 被设置时，使用该选项
- JDK中ALPN可用时使用 {@link io.vertx.core.net.JdkSSLEngineOptions}
- OpenSSL中ALPN可用时使用 {@link io.vertx.core.net.OpenSSLEngineOptions}
- 否则失败

===== OpenSSL ALPN支持

OpenSSL提供了原生的ALPN支持。

OpenSSL需要配置 {@link io.vertx.core.net.TCPSSLOptions#setOpenSslEngineOptions(OpenSSLEngineOptions)}
并在类路径上使用 http://netty.io/wiki/forked-tomcat-native.html[netty-tcnative] 的jar库。依赖于tcnative的实现它需要OpenSSL安装在您的操作系统中。

===== Jetty-ALPN支持

Jetty-ALPN是一个小型的jar，它覆盖了几种Java 8发行版用以支持ALPN。

JVM必须将 `alpn-boot-${version}.jar` 放在它的 `boot classpath` 中启动：

----
-Xbootclasspath/p:/path/to/alpn-boot${version}.jar
----

其中 `${version}` 取决于JVM的版本，如 *OpenJDK 1.8.0u74* 中的 *8.1.7.v20160121*。这个完整列表可以在 http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html[Jetty-ALPN page]
页面上找到。

这种方法主要缺点是ALPN的实现版本依赖于JVM的版本。

为了解决这个问题，可以使用 _https://github.com/jetty-project/jetty-alpn-agent[Jetty ALPN agent]_ 。agent是一个JVM代理，它会为运行它的JVM选择正确的ALPN版本：

----
-javaagent:/path/to/alpn/agent
----

=== 客户端连接使用代理

{@link io.vertx.core.net.NetClient} 支持HTTP/1.x *CONNECT*、*SOCKS4a* 或 *SOCKS5* 代理。

代理可以在 {@link io.vertx.core.net.NetClientOptions} 内设置
{@link io.vertx.core.net.ProxyOptions} 来配置代理类型、主机名、端口、可选的用户名和密码。

以下是一个例子：

[source,$lang]

----
{@link examples.NetExamples#example47}
----

DNS 解析总是在代理服务器上完成解析，为了实现 SOCKS4 客户端的功能，需要先在本地解析 DNS 地址。
