== 记录解析器

记录解析器（Record Parser）允许您轻松解析由字节序列或固定尺寸带分隔符的记录的协议。
它将输入缓冲区序列转换为已配置的缓冲区序列（固定大小或带分隔符的记录）。

例如，若您使用 `\n` 分割的简单ASCII文本协议，并输入如下：

[source]
----
buffer1:HELLO\nHOW ARE Y
buffer2:OU?\nI AM
buffer3: DOING OK
buffer4:\n
----

记录解析器将生成下结果：

[source]
----
buffer1:HELLO
buffer2:HOW ARE YOU?
buffer3:I AM DOING OK
----

我们来看看相关代码：

[source, $lang]
----
{@link examples.ParseToolsExamples#recordParserExample1()}
----

我们还可以生成固定尺寸的块，如下：

[source, $lang]
----
{@link examples.ParseToolsExamples#recordParserExample2()}
----

有关更多详细信息，请查看 {@link io.vertx.core.parsetools.RecordParser} 类。

== Json Parser

You can easily parse JSON structures but that requires to provide the JSON content at once, but it
may not be convenient when you need to parse very large structures.

The non-blocking JSON parser is an event driven parser able to deal with very large structures.
It transforms a sequence of input buffer to a sequence of JSON parse events.

[source, $lang]
----
{@link examples.ParseToolsExamples#jsonParserExample1()}
----

The parser is non-blocking and emitted events are driven by the input buffers.

[source, $lang]
----
{@link examples.ParseToolsExamples#jsonParserExample2}
----

Event driven parsing provides more control but comes at the price of dealing with fine grained events, which can be
inconvenient sometimes. The JSON parser allows you to handle JSON structures as values when it is desired:

[source, $lang]
----
{@link examples.ParseToolsExamples#jsonParserExample3}
----

The value mode can be set and unset during the parsing allowing you to switch between fine grained
events or JSON object value events.

[source, $lang]
----
{@link examples.ParseToolsExamples#jsonParserExample4}
----

You can do the same with arrays as well

[source, $lang]
----
{@link examples.ParseToolsExamples#jsonParserExample5}
----

You can also decode POJOs

[source, $lang]
----
{@link examples.ParseToolsExamples#jsonParserExample6}
----

Whenever the parser fails to process a buffer, an exception will be thrown unless you set an exception handler:

[source, $lang]
----
{@link examples.ParseToolsExamples#jsonParserExample7}
----

The parser also parses json streams:

- concatenated json streams: `{"temperature":30}{"temperature":50}`
- line delimited json streams: `{"an":"object"}\r\n3\r\n"a string"\r\nnull`

For more details, check out the {@link io.vertx.core.parsetools.JsonParser} class.
