= Vert.x Web Client
:toc: left
:lang: $lang
:$lang: $lang

Vert.x Web Client（Web客户端）是一个异步的 HTTP 和 HTTP/2 客户端。

Web Client使得发送 HTTP 请求以及从 Web 服务器接收 HTTP 响应变得更加便捷，同时提供了额外的高级功能，例如：

* JSON体的编码和解码
* 请求和响应泵
* 请求参数的处理
* 统一的错误处理
* 提交表单

制作Web Client的目的并非为了替换Vert.x Core中的 {@link io.vertx.core.http.HttpClient} ，
而是基于该客户端，扩展并保留其便利的设置和特性，例如请求连接池（Pooling），HTTP/2的支持，
流水线／管线的支持等。当您需要对 HTTP 请求和响应做细微粒度控制时，您应当使用
{@link io.vertx.core.http.HttpClient} 。

另外Web Client并未提供 WebSocket API，此时您应当使用 {@link io.vertx.core.http.HttpClient} 。

== 使用Web Client

如需使用Vert.x Web Client，请先加入以下依赖：

* Maven (在 `pom.xml` 文件中):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-web-client</artifactId>
  <version>${maven.version}</version>
</dependency>
----

* Gradle (在 `build.gradle` 文件中):

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'io.vertx:vertx-web-client:${maven.version}'
}
----

== 对Vert.x Core HTTP Client的回顾

Vert.x Web Client使用Vert.x Core的API，如您对此还不熟悉，请先熟悉
{@link io.vertx.core.http.HttpClient} 的一些基本概念。

== 创建Web Client

您可使用缺省设置创建一个 {@link io.vertx.ext.web.client.WebClient} ：

[source,$lang]
----
{@link examples.WebClientExamples#create}
----

您亦可使用配置选项来创建客户端：

[source,$lang]
----
{@link examples.WebClientExamples#createFromOptions}
----

Web Client配置选项继承自 `HttpClient` 配置选项，使用时可根据实际情况选择。

如已在程序中创建 `HttpClient`，可用以下方式复用：

[source,$lang]
----
{@link examples.WebClientExamples#wrap(io.vertx.core.http.HttpClient)}
----

== 发送请求

=== 无请求体的简单请求

一般情况下，HTTP GET，OPTIONS以及HEAD请求没有请求体，可用以下方式发送无请求体的HTTP Requests（HTTP请求）：

[source,$lang]
----
{@link examples.WebClientExamples#simpleGetAndHead}
----

您可用以下链式方式向请求URI添加查询参数

[source,$lang]
----
{@link examples.WebClientExamples#simpleGetWithParams(io.vertx.ext.web.client.WebClient)}
----

在请求URI中的参数将会被预填充

[source,$lang]
----
{@link examples.WebClientExamples#simpleGetWithInitialParams(io.vertx.ext.web.client.WebClient)}
----

设置请求URI将会自动清除已有的查询参数

[source,$lang]
----
{@link examples.WebClientExamples#simpleGetOverwritePreviousParams(io.vertx.ext.web.client.WebClient)}
----

=== 填充请求体

如需要发送请求体，可使用相同的API并在最后加上 `sendXXX` 方法发送相应的请求体。

例如用 {@link io.vertx.ext.web.client.HttpRequest#sendBuffer} 方法发送一个缓冲体：

[source,$lang]
----
{@link examples.WebClientExamples#sendBuffer(io.vertx.ext.web.client.WebClient, io.vertx.core.buffer.Buffer)}
----

有时候我们并不希望将所有数据一次性全部读入内存，因为文件太大或希望同时处理多个请求，希望每个请求仅使用最小的内存。出于此目的，Web Client可用
{@link io.vertx.ext.web.client.HttpRequest#sendStream} 方法发送流式数据 `ReadStream<Buffer>`
（例如 `{@link io.vertx.core.file.AsyncFile}` 便是一个 `ReadStream<Buffer>`）：

[source,$lang]
----
{@link examples.WebClientExamples#sendStreamChunked(io.vertx.ext.web.client.WebClient, io.vertx.core.streams.ReadStream)}
----

Web Client会为您设置好传输泵以平滑传输流。如果流长度未知则使用分块传输（chunked transfer）。

如已知流的大小，可在HTTP协议头中设置 `content-length` 属性

[source,$lang]
----
{@link examples.WebClientExamples#sendStream(io.vertx.ext.web.client.WebClient, io.vertx.core.file.FileSystem)}
----

此时POST方法不会使用分块传输。

==== JSON体

有时您需要在请求体中使用JSON格式，可使用 {@link io.vertx.ext.web.client.HttpRequest#sendJsonObject(io.vertx.core.json.JsonObject, io.vertx.core.Handler)} 方法发送 {@link io.vertx.core.json.JsonObject} ：

[source,$lang]
----
{@link examples.WebClientExamples#sendJsonObject(io.vertx.ext.web.client.WebClient)}
----

在Java，Groovy以及Kotlin语言中，您亦可使用 {@link io.vertx.ext.web.client.HttpRequest#sendJson} 方法发送POJO（Plain Old Java Object），该方法会自动调用 {@link io.vertx.core.json.Json#encode(java.lang.Object)}
方法将 POJO 映射为 JSON：

[source,$lang]
----
{@link examples.WebClientExamples#sendJsonPOJO(io.vertx.ext.web.client.WebClient)}
----

NOTE: {@link io.vertx.core.json.Json#encode(java.lang.Object)} 方法使用Jackson的 mapper将 POJO 映射成 JSON。

==== 表单提交

您可使用 {@link io.vertx.ext.web.client.HttpRequest#sendForm(io.vertx.core.MultiMap, io.vertx.core.Handler)}
 方法发送HTTP表单。

[source,$lang]
----
{@link examples.WebClientExamples#sendForm(io.vertx.ext.web.client.WebClient)}
----

缺省情况下，提交表单的请求头中的 `content-type` 属性值为 `application/x-www-form-urlencoded`，您亦可将其设置为 `multipart/form-data`：

[source,$lang]
----
{@link examples.WebClientExamples#sendMultipart(io.vertx.ext.web.client.WebClient)}
----

If you want to upload files and send attributes, you can create a {@link io.vertx.ext.web.multipart.MultipartForm} and
 use {@link io.vertx.ext.web.client.HttpRequest#sendMultipartForm(io.vertx.ext.web.multipart.MultipartForm, io.vertx.core.Handler)}.

[source,$lang]
----
{@link examples.WebClientExamples#sendMultipartWithFileUpload(io.vertx.ext.web.client.WebClient)}
----

=== 填充请求头

您可使用以下方式填充请求头：

[source,$lang]
----
{@link examples.WebClientExamples#sendHeaders1(io.vertx.ext.web.client.WebClient)}
----

此处 Headers 是一个 {@link io.vertx.core.MultiMap} 对象，提供了增加、设置以及删除头属性操作的入口。HTTP头的某些特定属性允许设置多个值。

您亦可通过 `putHeader` 方法写入头属性：

[source,$lang]
----
{@link examples.WebClientExamples#sendHeaders2(io.vertx.ext.web.client.WebClient)}
----

=== 重用请求

{@link io.vertx.ext.web.client.HttpRequest#send(io.vertx.core.Handler)} 方法可被重复多次调用，这使得配置以及重用
{@link io.vertx.ext.web.client.HttpRequest} 对象变得更加便捷：

[source,$lang]
----
{@link examples.WebClientExamples#multiGet(io.vertx.ext.web.client.WebClient)}
----

请注意， {@link io.vertx.ext.web.client.HttpRequest} 对象是可变的。
所以在修改缓存中的对象之前，您应当使用 {@link io.vertx.ext.web.client.HttpRequest#copy()} 方法先复制一份拷贝：

[source,$lang]
----
{@link examples.WebClientExamples#multiGetCopy(io.vertx.ext.web.client.WebClient)}
----

=== 超时

您可通过 {@link io.vertx.ext.web.client.HttpRequest#timeout(long)} 方法设置超时时间。

[source,$lang]
----
{@link examples.WebClientExamples#timeout(io.vertx.ext.web.client.WebClient)}
----

若请求在设定时间内没返回任何数据，则一个超时异常将会传递给响应处理代码。

== 处理HTTP响应

Web Client请求发送之后，返回的结果将会被包装在异步结果 {@link io.vertx.ext.web.client.HttpResponse} 中。

当响应被成功接收到之后，相应的回调函数将会被触发。

[source,$lang]
----
{@link examples.WebClientExamples#receiveResponse(io.vertx.ext.web.client.WebClient)}
----

WARNING: 缺省状况下，响应会被完全缓冲读入内存，请用 {@link io.vertx.ext.web.codec.BodyCodec#pipe(io.vertx.core.streams.WriteStream)} 方法将响应写入流。

=== 响应编解码器

缺省状况下，响应以缓冲形式提供，并不提供任何形式的解码。

可用 {@link io.vertx.ext.web.codec.BodyCodec} 将响应定制成以下类型：

* 普通字符串
* JSON对象
* 将JSON映射成POJO
* {@link io.vertx.core.streams.WriteStream}

响应体编解码器对二进制数据流解码，以节省您在响应处理中的代码。

使用 {@link io.vertx.ext.web.codec.BodyCodec#jsonObject()} 将结果解码为JSON对象：

[source,$lang]
----
{@link examples.WebClientExamples#receiveResponseAsJsonObject(io.vertx.ext.web.client.WebClient)}
----

在Java，Groovy以及Kotlin语言中，JSON对象可被解码映射成POJO：

[source,$lang]
----
{@link examples.WebClientExamples#receiveResponseAsJsonPOJO(io.vertx.ext.web.client.WebClient)}
----

当响应结果较大时，请使用 {@link io.vertx.ext.web.codec.BodyCodec#pipe(io.vertx.core.streams.WriteStream)}
方法。响应体编解码器将响应结果压入 {@link io.vertx.core.streams.WriteStream}
并在最后发出成功或失败的信号。

[source,$lang]
----
{@link examples.WebClientExamples#receiveResponseAsWriteStream(io.vertx.ext.web.client.WebClient, io.vertx.core.streams.WriteStream)}
----

最后，如您对响应结果不感兴趣，可用 {@link io.vertx.ext.web.codec.BodyCodec#none()}
废弃响应体。

[source,$lang]
----
{@link examples.WebClientExamples#receiveResponseAndDiscard(io.vertx.ext.web.client.WebClient)}
----

若无法预知响应内容类型，您依旧可以在获取结果之后，用 `bodyAsXXX()` 方法将其转换成特定的类型

[source,$lang]
----
{@link examples.WebClientExamples#receiveResponseAsBufferDecodeAsJsonObject(io.vertx.ext.web.client.WebClient)}
----

WARNING: 这种方式仅对响应结果为缓冲体有效。

=== 处理30x重定向

缺省状况下，客户端将会依照30x状态码自动重定向，您可使用 {@link io.vertx.ext.web.client.WebClientOptions} 予以配置：

[source,$lang]
----
{@link examples.WebClientExamples#testClientDisableFollowRedirects(io.vertx.core.Vertx)}
----

客户端将会执行最多达`16`次重定向，该参数亦可在 {@link io.vertx.ext.web.client.WebClientOptions} 配置：

[source,$lang]
----
{@link examples.WebClientExamples#testClientChangeMaxRedirects(io.vertx.core.Vertx)}
----

== 使用HTTPS

Vert.x Web Client可用与 {@link io.vertx.core.http.HttpClient} 相同方式配置HTTPS协议。

您可对每个请求单独设置：

[source,$lang]
----
{@link examples.WebClientExamples#testOverrideRequestSSL(io.vertx.ext.web.client.WebClient)}
----

或使用绝对路径：

[source,$lang]
----
{@link examples.WebClientExamples#testAbsRequestSSL(io.vertx.ext.web.client.WebClient)}
----

ifdef::java[]
include::override/rxjava.adoc[]
endif::[]
