== Vert.x Common SQL interface

Vert.x Common SQL Interface组件定义了 Vert.x 与各种 SQL 服务交互的方法。

您必须通过使用特定的 SQL 服务（例如 JDBC/MySQL/PostgreSQL）的接口来获取数据库连接。

要使用此组件，需要添加下列依赖：

* Maven (在 `pom.xml`文件中):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-sql-common</artifactId>
  <version>${maven.version}</version>
</dependency>
----

* Gradle (在 `build.gradle` 文件中):

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-sql-common:${maven.version}'
----

== Simple SQL Operations

There are times when you will want to run a single SQL operation, e.g.: a single select of a row, or a update to a
set of rows which do not require to be part of a transaction or have dependencies on the previous or next operation.

For these cases, clients provide a boilerplate-less API {@link io.vertx.ext.sql.SQLOperations}. This interface will
perform the following steps for you:

1. acquire a connection from the connection pool
2. perform your action
3. close and return the connection to the connection pool

An example where users get loaded from the `USERS` table could be:

[source,$lang]
----
{@link examples.SQLExamples#example16}
----

You can perform the following operations as a simple one "shot" method call:

* {@link io.vertx.ext.sql.SQLClient#query(java.lang.String, io.vertx.core.Handler)}
* {@link io.vertx.ext.sql.SQLClient#queryWithParams(java.lang.String, io.vertx.core.json.JsonArray, io.vertx.core.Handler)}
* {@link io.vertx.ext.sql.SQLClient#querySingle(java.lang.String, io.vertx.core.Handler)}
* {@link io.vertx.ext.sql.SQLClient#querySingleWithParams(java.lang.String, io.vertx.core.json.JsonArray, io.vertx.core.Handler)}
* {@link io.vertx.ext.sql.SQLClient#update(java.lang.String, io.vertx.core.Handler)}
* {@link io.vertx.ext.sql.SQLClient#updateWithParams(java.lang.String, io.vertx.core.json.JsonArray, io.vertx.core.Handler)}
* {@link io.vertx.ext.sql.SQLClient#call(java.lang.String, io.vertx.core.Handler)}
* {@link io.vertx.ext.sql.SQLClient#callWithParams(java.lang.String, io.vertx.core.json.JsonArray, io.vertx.core.json.JsonArray, io.vertx.core.Handler)}

For further details on these API please refer to the {@link io.vertx.ext.sql.SQLOperations} interface.


== SQL 连接

我们用 {@link io.vertx.ext.sql.SQLConnection} 接口来表示数据库连接（译者注：此接口中包含各种基本的操作方法）。

=== 自动提交

当您获取的数据库连接，其自动提交选项（auto commit）默认设置为 `true`。这意味着您的每个操作都将在单独的事务中有效执行。

如果您希望在同一个事务中执行多个操作，就应该使用
{@link io.vertx.ext.sql.SQLConnection#setAutoCommit(boolean, io.vertx.core.Handler)} 方法设置自动提交为`false`。

当操作完成时，回调方法将会被执行：

[source,$lang]
----
{@link examples.SQLExamples#example1}
----

=== 执行查询

您可以使用 {@link io.vertx.ext.sql.SQLConnection#query(java.lang.String, io.vertx.core.Handler)} 方法执行查询操作。

查询语句（原生SQL）传给数据库时，不会经过任何修改。

当查询结束时，将执行回调方法处理结果。查询结果包装在 {@link io.vertx.ext.sql.ResultSet} 中。

[source,$lang]
----
{@link examples.SQLExamples#example2}
----

{@link io.vertx.ext.sql.ResultSet} 类代表查询结果。

您可以通过 {@link io.vertx.ext.sql.ResultSet#getColumnNames()} 方法获得查询结果的列名 List 集合，实际的结果集可以通过
{@link io.vertx.ext.sql.ResultSet#getResults()} 方法获得。

结果集被包装成了一组 {@link io.vertx.core.json.JsonArray} 列表，其中的每个元素代表一行结果。

[source,$lang]
----
{@link examples.SQLExamples#example3}
----

您还可以使用 {@link io.vertx.ext.sql.ResultSet#getRows()} -
方法来获得被包装成了 JSON 对象列表（`List<JsonObject> `）的结果集，这样能让 API 的操作更简单些。
但要注意的是，查询出的结果集中可能会出现重复的列名。
若遇到这样的情况，您应该选择使用 {@link io.vertx.ext.sql.ResultSet#getResults()} 方法。

下面是将结果集作为 `JsonObject` 进行迭代的例子：

[source,$lang]
----
{@link examples.SQLExamples#example3__1}
----

=== 预编译查询

您可以使用
{@link io.vertx.ext.sql.SQLConnection#queryWithParams(java.lang.String, io.vertx.core.json.JsonArray, io.vertx.core.Handler)}
方法执行预编译查询（prepared statement queries）。

此方法接受含参数占位符的SQL查询语句以及 {@link io.vertx.core.json.JsonArray} 对象（用于传递参数）或参数值。

[source,$lang]
----
{@link examples.SQLExamples#example3_1}
----

=== 执行 INSERT/UPDATE/DELETE 语句

您可以使用 {@link io.vertx.ext.sql.SQLConnection#update(java.lang.String, io.vertx.core.Handler)} 方法来执行更新数据库的操作（包括增、删、改）。

更新语句（原生SQL）传给数据库时，不会经过任何处理。

当更新结束时，将执行回调方法处理结果。更新结果包装在 {@link io.vertx.ext.sql.UpdateResult} 对象中。

您可以通过 {@link io.vertx.ext.sql.UpdateResult#getUpdated()} 方法获得更新的数据条数，并且如果更新操作有生成主键，可以通过 {@link io.vertx.ext.sql.UpdateResult#getKeys()} 方法获得对应的主键。

[source,$lang]
----
{@link examples.SQLExamples#example4}
----

=== 预编译更新

您可以使用
{@link io.vertx.ext.sql.SQLConnection#updateWithParams(java.lang.String, io.vertx.core.json.JsonArray, io.vertx.core.Handler)}
方法来执行预编译更新（prepared statement updates）。

此方法接受含参数占位符的SQL更新语句以及 {@link io.vertx.core.json.JsonArray}
对象（用于传递参数）或参数值。

[source,$lang]
----
{@link examples.SQLExamples#example5}
----

=== 可调用语句

您可以使用
{@link io.vertx.ext.sql.SQLConnection#callWithParams(java.lang.String, io.vertx.core.json.JsonArray, io.vertx.core.json.JsonArray, io.vertx.core.Handler)}
方法来执行可调用语句（callable statements），例如 SQL 函数或者存储过程。

可调用语句。可以使用标准 JDBC 格式 `{ call func_proc_name() }`, 也可以选择使用占位符传参数的形式，例如： `{ call func_proc_name(?, ?) }`, 输入参数集（`params`）， {@link io.vertx.core.json.JsonArray} 类型，
包含输出类型的输出结果集（`output`）， {@link io.vertx.core.json.JsonArray} 类型，例如：`[null, 'VARCHAR']`， 对应的回调函数（`resultHandler`）

请注意，输出结果集的 {@link io.vertx.core.json.JsonArray} 的下标和输入参数的  {@link io.vertx.core.json.JsonArray} 同样重要。
如果第二个参数代表输出结果集，那么应该设置结果集的  {@link io.vertx.core.json.JsonArray} 的第一个元素为 null。

有些 SQL 函数只使用 `return` 关键字返回输出结果集，这时可以这样调用：

[source,$lang]
----
{@link examples.SQLExamples#example8}
----

但是当您使用存储过程时，还是需要使用它的参数来返回结果集。如果一个存储过程没有返回值的话，可以像下面这样调用：

[source,$lang]
----
{@link examples.SQLExamples#example9}
----

但是如果存储过程有返回值的话，需要像下面这样调用：

[source,$lang]
----
{@link examples.SQLExamples#example10}
----

请注意：输入输出参数的下标必须匹配 `?` 的下标，并且输出结果集元素的值必须是结果集类型的字符串表示。

为避免歧义，实现类需要遵循以下规则（译者注：可参考 Vert.x JDBC Client 的实现源码 [`JDBCStatementHelper.fillStatement(statement, in, out)`](https://github.com/vert-x3/vertx-jdbc-client/blob/master/src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCStatementHelper.java#L97)）：

* 当 `IN` 参数的元素是 `NOT NULL` 时，此元素将被注册为输入参数
* 当 `IN` 参数的元素是 null 时，将进一步去检查 `OUT` 参数的元素值，再做判断
 若当 `IN` 参数的元素是 null，且 `OUT` 参数的元素值不是 null 时，`OUT` 参数的元素值将被注册为输出参数
 若当 `IN` 参数的元素是 null，且 `OUT` 参数的元素值也是 null 时， `IN` 参数的元素将被当作 `NULL` 值传入存储过程

注册为 `OUT` 的参数，设置成了 `ResultSet` 的 `output` 属性。

=== 批量操作

Vert.x SQL 公共接口定义了3种批量操作的方法：

* 批量操作 {@link io.vertx.ext.sql.SQLConnection#batch(java.util.List, io.vertx.core.Handler)}
* 批量预编译操作 {@link io.vertx.ext.sql.SQLConnection#batchWithParams(java.lang.String, java.util.List, io.vertx.core.Handler)}
* 批量调用语句 {@link io.vertx.ext.sql.SQLConnection#batchCallableWithParams(java.lang.String, java.util.List, java.util.List, io.vertx.core.Handler)}

批量操作能执行一组 SQL 语句（`List` 类型），例如：

[source,$lang]
----
{@link examples.SQLExamples#example12}
----

预编译或者调用语句将会根据参数列表，来重复使用 SQL 语句，例如：

[source,$lang]
----
{@link examples.SQLExamples#example11}
----

=== 执行其他操作

若需要执行其他数据库操作，例如您可以使用
{@link io.vertx.ext.sql.SQLConnection#execute(java.lang.String, io.vertx.core.Handler)} 方法来执行 `CREATE TABLE` 语句。

SQL语句传给数据库时，不会经过任何处理。操作结束时将调用回调方法。

[source,$lang]
----
{@link examples.SQLExamples#example6}
----

=== 返回多个结果集

某些情况下，您的查询语句可能返回多个结果集 `ResultSet`，
此时，返回的结果集会被转成纯 JSON，并且为了保持稳定性，下一个 `ResultSet` 被作为当前 `ResultSet` 的 `next` 属性链接着。一种简单的遍历所有结果集的方式如下：

[source,$lang]
----
{@link examples.SQLExamples#example13}
----

=== Streaming

在处理大数据结果集时，不建议使用上面提到的API，而是使用数据流（stream data）的方式。因为它能够避免把所有的返回值加载到内存中，而且得到的 JSON 格式的数据也能够一行行的处理，例如：

[source,$lang]
----
{@link examples.SQLExamples#example14}
----

您还可以控制 Stream 何时停止，何时恢复，何时结束。对于查询返回多个结果集的情况，您应该使用 ended event 来获得下一个结果集。如果有，Stream 将会得到新的结果集，若没有，将会调用结束方法。

[source,$lang]
----
{@link examples.SQLExamples#example15}
----

=== 使用事务

要使用事务，首先要用 {@link io.vertx.ext.sql.SQLConnection#setAutoCommit(boolean, io.vertx.core.Handler)} 方法设置 auto-commit 为 `false`。

然后您就可以执行在同一个事务中的操作，在需要提交事务时，调用
{@link io.vertx.ext.sql.SQLConnection#commit(io.vertx.core.Handler)} 方法；在需要回滚时，调用
{@link io.vertx.ext.sql.SQLConnection#rollback(io.vertx.core.Handler)} 方法。

一旦 `commit`/`rollback` 方法执行结束，将会调用回调方法。然后下一个事务也将自动开始。

[source,$lang]
----
{@link examples.SQLExamples#example7}
----

=== 关闭连接

您在用完连接后，必须使用 {@link io.vertx.ext.sql.SQLConnection#close(io.vertx.core.Handler)} 方法把连接返回给连接池。
